{{ config(
    materialized = 'table',
    database = 'PORTFOLIO_DB',
    schema = 'MARTS'
) }}


WITH TXN_SUMMARISED AS (
    SELECT  
        PD.TRANSACTION_DATE,
        PD.STORE_ID,
        PD.SALES_CHANNEL,
        PD.SALES_TYPE,
        PD.TRANSACTION_TIME_BINNED_30,
    
        COUNT(DISTINCT PD.TRANSACTION_ID) AS TRANSACTION_COUNT,
    
        COUNT(
            DISTINCT CASE 
                WHEN PD.MEMBER_ID IS NOT NULL 
                THEN PD.TRANSACTION_ID 
            END
        ) AS TRANSACTION_COUNT_MEMBER,
    
        SUM(AMOUNT_NET) AS AMOUNT_NET,
    
        SUM(
             CASE 
                WHEN PD.MEMBER_ID IS NOT NULL 
                THEN PD.AMOUNT_NET 
            END
        ) AS AMOUNT_NET_MEMBER,
    
        SUM(AMOUNT_GST) AS AMOUNT_GST,
    
        SUM(
             CASE 
                WHEN PD.MEMBER_ID IS NOT NULL 
                THEN PD.AMOUNT_GST 
            END
        ) AS AMOUNT_GST_MEMBER
    
    
    FROM {{ ref('STG_PRODUCT_DATA') }} PD
    
    -- WHERE PD.TRANSACTION_DATE = DATE '2026-03-03' AND PD.STORE_ID = 22 --FOR TESTING
    
    GROUP BY
        PD.TRANSACTION_DATE,
        PD.STORE_ID,
        PD.SALES_CHANNEL,
        PD.SALES_TYPE,
        PD.TRANSACTION_TIME_BINNED_30
)

,TABLE_PLUS_HOLIDAY AS (
SELECT TX.*, DR.STATE
FROM TXN_SUMMARISED TX
LEFT JOIN {{ ref('STG_DIM_RESTAURANTS') }} DR ON
DR.STORE_ID = TX.STORE_ID
)

SELECT TP.*, PH.HOLIDAY_NAME
FROM TABLE_PLUS_HOLIDAY TP
LEFT JOIN {{ ref('STG_DIM_PUBLIC_HOLIDAYS') }} PH ON
TP.TRANSACTION_DATE = TRY_TO_DATE(PH.HOLIDAY_DATE, 'DD/MM/YYYY')
AND
TP.STATE = PH.STATE
