{{ config(
    materialized = 'table',
    database = 'PORTFOLIO_DB',
    schema = 'MARTS'
) }}

WITH BASE AS (
    SELECT
        TRY_TO_DATE(SNAPSHOT_DATE) AS SNAPSHOT_DATE,
        RESTAURANT_ID,
        PRODUCT_ID,
        COALESCE(OPENING_STOCK_QTY, 0) AS OPENING_STOCK_QTY,
        COALESCE(RECEIVED_QTY, 0) AS RECEIVED_QTY,
        COALESCE(USAGE_QTY, 0) AS USAGE_QTY,
        COALESCE(WASTAGE_QTY, 0) AS WASTAGE_QTY,
        COALESCE(ADJUSTMENT_QTY, 0) AS ADJUSTMENT_QTY,
        COALESCE(CLOSING_STOCK_QTY, 0) AS CLOSING_STOCK_QTY,
        COALESCE(REORDER_POINT_QTY, 0) AS REORDER_POINT_QTY,
        COALESCE(TARGET_STOCK_QTY, 0) AS TARGET_STOCK_QTY,
        COALESCE(UNIT_COST, 0) AS UNIT_COST,
        COALESCE(INVENTORY_VALUE, 0) AS SOURCE_INVENTORY_VALUE,
        COALESCE(STOCKOUT_FLAG, FALSE) AS STOCKOUT_FLAG,
        COALESCE(BELOW_REORDER_FLAG, FALSE) AS BELOW_REORDER_FLAG
    FROM {{ ref('STG_OPS_FACT_INVENTORY_DAILY') }}
),
CALCULATED AS (
    SELECT
        *,
        OPENING_STOCK_QTY
            + RECEIVED_QTY
            - USAGE_QTY
            - WASTAGE_QTY
            + ADJUSTMENT_QTY AS EXPECTED_CLOSING_STOCK_QTY,
        (OPENING_STOCK_QTY + CLOSING_STOCK_QTY) / 2.0 AS AVERAGE_INVENTORY_QTY,
        AVG(USAGE_QTY) OVER (
            PARTITION BY RESTAURANT_ID, PRODUCT_ID
            ORDER BY SNAPSHOT_DATE
            ROWS BETWEEN 6 PRECEDING AND CURRENT ROW
        ) AS AVG_DAILY_USAGE_7D,
        AVG(USAGE_QTY) OVER (
            PARTITION BY RESTAURANT_ID, PRODUCT_ID
            ORDER BY SNAPSHOT_DATE
            ROWS BETWEEN 27 PRECEDING AND CURRENT ROW
        ) AS AVG_DAILY_USAGE_28D
    FROM BASE
)
SELECT
    MD5(CONCAT_WS('|', SNAPSHOT_DATE::VARCHAR, RESTAURANT_ID, PRODUCT_ID)) AS INVENTORY_PERFORMANCE_KEY,
    SNAPSHOT_DATE,
    RESTAURANT_ID,
    PRODUCT_ID,
    OPENING_STOCK_QTY,
    RECEIVED_QTY,
    USAGE_QTY,
    WASTAGE_QTY,
    ADJUSTMENT_QTY,
    CLOSING_STOCK_QTY,
    REORDER_POINT_QTY,
    TARGET_STOCK_QTY,
    UNIT_COST,
    SOURCE_INVENTORY_VALUE,
    CLOSING_STOCK_QTY * UNIT_COST AS CALCULATED_INVENTORY_VALUE,
    OPENING_STOCK_QTY * UNIT_COST AS OPENING_INVENTORY_VALUE,
    RECEIVED_QTY * UNIT_COST AS RECEIVED_VALUE,
    USAGE_QTY * UNIT_COST AS USAGE_COST,
    WASTAGE_QTY * UNIT_COST AS WASTAGE_COST,
    ADJUSTMENT_QTY * UNIT_COST AS ADJUSTMENT_VALUE,
    AVERAGE_INVENTORY_QTY,
    AVERAGE_INVENTORY_QTY * UNIT_COST AS AVERAGE_INVENTORY_VALUE,
    EXPECTED_CLOSING_STOCK_QTY,
    CLOSING_STOCK_QTY - EXPECTED_CLOSING_STOCK_QTY AS INVENTORY_VARIANCE_QTY,
    (CLOSING_STOCK_QTY - EXPECTED_CLOSING_STOCK_QTY) * UNIT_COST AS INVENTORY_VARIANCE_VALUE,
    CLOSING_STOCK_QTY / NULLIF(TARGET_STOCK_QTY, 0) AS STOCK_TO_TARGET_RATIO,
    GREATEST(REORDER_POINT_QTY - CLOSING_STOCK_QTY, 0) AS REORDER_GAP_QTY,
    TARGET_STOCK_QTY - CLOSING_STOCK_QTY AS TARGET_GAP_QTY,
    GREATEST(TARGET_STOCK_QTY - CLOSING_STOCK_QTY, 0) * UNIT_COST AS ESTIMATED_REORDER_VALUE,
    AVG_DAILY_USAGE_7D,
    AVG_DAILY_USAGE_28D,
    CLOSING_STOCK_QTY / NULLIF(AVG_DAILY_USAGE_7D, 0) AS DAYS_OF_STOCK_7D,
    CLOSING_STOCK_QTY / NULLIF(AVG_DAILY_USAGE_28D, 0) AS DAYS_OF_STOCK_28D,
    STOCKOUT_FLAG,
    BELOW_REORDER_FLAG,
    IFF(CLOSING_STOCK_QTY <= 0, TRUE, FALSE) AS CALCULATED_STOCKOUT_FLAG,
    IFF(CLOSING_STOCK_QTY < REORDER_POINT_QTY, TRUE, FALSE) AS CALCULATED_BELOW_REORDER_FLAG,
    CURRENT_TIMESTAMP() AS CREATED_AT
FROM CALCULATED