{{ config(
    materialized = 'table',
    database = 'PORTFOLIO_DB',
    schema = 'MARTS'
) }}

WITH PURCHASE_ORDERS AS (
    SELECT
        PURCHASE_ORDER_ID,
        TRY_TO_DATE(ORDER_DATE) AS ORDER_DATE,
        RESTAURANT_ID,
        SUPPLIER_ID,
        PRODUCT_ID,
        COALESCE(ORDERED_QTY, 0) AS PO_ORDERED_QTY,
        COALESCE(UNIT_COST, 0) AS PURCHASE_ORDER_UNIT_COST,
        COALESCE(ORDER_VALUE, 0) AS SOURCE_ORDER_VALUE,
        TRY_TO_DATE(PROMISED_DELIVERY_DATE) AS PO_PROMISED_DELIVERY_DATE,
        PURCHASE_ORDER_STATUS
    FROM {{ ref('STG_OPS_FACT_PURCHASE_ORDERS') }}
),
DELIVERIES AS (
    SELECT
        DELIVERY_ID,
        PURCHASE_ORDER_ID,
        SUPPLIER_ID,
        RESTAURANT_ID,
        PRODUCT_ID,
        TRY_TO_DATE(PROMISED_DELIVERY_DATE) AS PROMISED_DELIVERY_DATE,
        TRY_TO_DATE(ACTUAL_DELIVERY_DATE) AS ACTUAL_DELIVERY_DATE,
        COALESCE(ORDERED_QTY, 0) AS ORDERED_QTY,
        COALESCE(RECEIVED_QTY, 0) AS RECEIVED_QTY,
        COALESCE(REJECTED_QTY, 0) AS REJECTED_QTY,
        COALESCE(ACCEPTED_QTY, 0) AS ACCEPTED_QTY,
        COALESCE(DELIVERY_DELAY_DAYS, 0) AS DELIVERY_DELAY_DAYS,
        COALESCE(ON_TIME_FLAG, FALSE) AS ON_TIME_FLAG,
        COALESCE(IN_FULL_FLAG, FALSE) AS IN_FULL_FLAG,
        COALESCE(OTIF_FLAG, FALSE) AS OTIF_FLAG,
        QUALITY_SCORE
    FROM {{ ref('STG_OPS_FACT_SUPPLIER_DELIVERIES') }}
)
SELECT
    D.DELIVERY_ID AS DELIVERY_PERFORMANCE_KEY,
    D.DELIVERY_ID,
    D.PURCHASE_ORDER_ID,
    D.SUPPLIER_ID,
    D.RESTAURANT_ID,
    D.PRODUCT_ID,
    P.ORDER_DATE,
    D.PROMISED_DELIVERY_DATE,
    D.ACTUAL_DELIVERY_DATE,
    D.ORDERED_QTY,
    D.RECEIVED_QTY,
    D.REJECTED_QTY,
    D.ACCEPTED_QTY,
    P.PURCHASE_ORDER_UNIT_COST,
    P.SOURCE_ORDER_VALUE,
    D.ORDERED_QTY * P.PURCHASE_ORDER_UNIT_COST AS CALCULATED_ORDER_VALUE,
    D.RECEIVED_QTY * P.PURCHASE_ORDER_UNIT_COST AS RECEIVED_VALUE,
    D.ACCEPTED_QTY * P.PURCHASE_ORDER_UNIT_COST AS ACCEPTED_VALUE,
    D.REJECTED_QTY * P.PURCHASE_ORDER_UNIT_COST AS REJECTED_VALUE,
    GREATEST(D.ORDERED_QTY - D.RECEIVED_QTY, 0) AS SHORT_DELIVERY_QTY,
    GREATEST(D.ORDERED_QTY - D.RECEIVED_QTY, 0) * P.PURCHASE_ORDER_UNIT_COST AS SHORT_DELIVERY_VALUE,
    D.RECEIVED_QTY / NULLIF(D.ORDERED_QTY, 0) AS FILL_RATE,
    D.ACCEPTED_QTY / NULLIF(D.RECEIVED_QTY, 0) AS ACCEPTANCE_RATE,
    D.REJECTED_QTY / NULLIF(D.RECEIVED_QTY, 0) AS REJECTION_RATE,
    DATEDIFF(DAY, P.ORDER_DATE, D.ACTUAL_DELIVERY_DATE) AS ACTUAL_LEAD_TIME_DAYS,
    DATEDIFF(DAY, P.ORDER_DATE, D.PROMISED_DELIVERY_DATE) AS PROMISED_LEAD_TIME_DAYS,
    D.DELIVERY_DELAY_DAYS,
    D.ON_TIME_FLAG,
    D.IN_FULL_FLAG,
    D.OTIF_FLAG,
    D.QUALITY_SCORE,
    P.PURCHASE_ORDER_STATUS,
    CASE
        WHEN D.OTIF_FLAG THEN 'ON_TIME_IN_FULL'
        WHEN NOT D.ON_TIME_FLAG AND NOT D.IN_FULL_FLAG THEN 'LATE_AND_SHORT'
        WHEN NOT D.ON_TIME_FLAG THEN 'LATE'
        WHEN NOT D.IN_FULL_FLAG THEN 'SHORT'
        ELSE 'OTHER'
    END AS DELIVERY_STATUS,
    CURRENT_TIMESTAMP() AS CREATED_AT
FROM DELIVERIES D
LEFT JOIN PURCHASE_ORDERS P
    ON D.PURCHASE_ORDER_ID = P.PURCHASE_ORDER_ID