
{{ config(
    materialized = 'table',
    database = 'PORTFOLIO_DB',
    schema = 'MARTS'
) }}
WITH SOURCE_DAILY AS (
    SELECT
        TRY_TO_DATE(WORK_DATE) AS WORK_DATE,
        RESTAURANT_ID,
        COALESCE(SCHEDULED_HOURS, 0) AS SOURCE_SCHEDULED_HOURS,
        COALESCE(ACTUAL_HOURS, 0) AS SOURCE_ACTUAL_HOURS,
        COALESCE(REGULAR_HOURS, 0) AS SOURCE_REGULAR_HOURS,
        COALESCE(OVERTIME_HOURS, 0) AS SOURCE_OVERTIME_HOURS,
        COALESCE(LABOUR_COST, 0) AS SOURCE_LABOUR_COST,
        COALESCE(ABSENCE_COUNT, 0) AS SOURCE_ABSENCE_COUNT,
        COALESCE(ESTIMATED_SALES, 0) AS SOURCE_ESTIMATED_SALES,
        LABOUR_COST_PCT_OF_SALES AS SOURCE_LABOUR_COST_PCT_OF_SALES,
        SALES_PER_LABOUR_HOUR AS SOURCE_SALES_PER_LABOUR_HOUR
    FROM {{ ref('STG_OPS_FACT_LABOUR_DAILY') }}
),
SHIFT_DAILY AS (
    SELECT
        TRY_TO_DATE(SHIFT_DATE) AS WORK_DATE,
        RESTAURANT_ID,
        COUNT(DISTINCT SHIFT_ID) AS SHIFT_COUNT,
        COUNT(DISTINCT EMPLOYEE_ID) AS EMPLOYEES_SCHEDULED_COUNT,
        COUNT(DISTINCT IFF(COALESCE(ACTUAL_HOURS, 0) > 0, EMPLOYEE_ID, NULL)) AS EMPLOYEES_WORKED_COUNT,
        SUM(COALESCE(SCHEDULED_HOURS, 0)) AS CALCULATED_SCHEDULED_HOURS,
        SUM(COALESCE(ACTUAL_HOURS, 0)) AS CALCULATED_ACTUAL_HOURS,
        SUM(COALESCE(REGULAR_HOURS, 0)) AS CALCULATED_REGULAR_HOURS,
        SUM(COALESCE(OVERTIME_HOURS, 0)) AS CALCULATED_OVERTIME_HOURS,
        SUM(COALESCE(LABOUR_COST, 0)) AS CALCULATED_LABOUR_COST,
        COUNT_IF(COALESCE(ABSENCE_FLAG, FALSE)) AS CALCULATED_ABSENCE_COUNT,
        COUNT_IF(COALESCE(NO_SHOW_FLAG, FALSE)) AS NO_SHOW_COUNT
    FROM {{ ref('STG_OPS_FACT_EMPLOYEE_SHIFTS') }}
    GROUP BY 1, 2
)
SELECT
    MD5(CONCAT_WS('|', S.WORK_DATE::VARCHAR, S.RESTAURANT_ID)) AS LABOUR_PERFORMANCE_KEY,
    S.WORK_DATE,
    S.RESTAURANT_ID,
    SH.SHIFT_COUNT,
    SH.EMPLOYEES_SCHEDULED_COUNT,
    SH.EMPLOYEES_WORKED_COUNT,
    S.SOURCE_SCHEDULED_HOURS,
    S.SOURCE_ACTUAL_HOURS,
    S.SOURCE_REGULAR_HOURS,
    S.SOURCE_OVERTIME_HOURS,
    S.SOURCE_LABOUR_COST,
    S.SOURCE_ABSENCE_COUNT,
    S.SOURCE_ESTIMATED_SALES,
    S.SOURCE_LABOUR_COST_PCT_OF_SALES,
    S.SOURCE_SALES_PER_LABOUR_HOUR,
    SH.CALCULATED_SCHEDULED_HOURS,
    SH.CALCULATED_ACTUAL_HOURS,
    SH.CALCULATED_REGULAR_HOURS,
    SH.CALCULATED_OVERTIME_HOURS,
    SH.CALCULATED_LABOUR_COST,
    SH.CALCULATED_ABSENCE_COUNT,
    SH.NO_SHOW_COUNT,
    SH.CALCULATED_ACTUAL_HOURS - SH.CALCULATED_SCHEDULED_HOURS AS SCHEDULE_VARIANCE_HOURS,
    (SH.CALCULATED_ACTUAL_HOURS - SH.CALCULATED_SCHEDULED_HOURS)
        / NULLIF(SH.CALCULATED_SCHEDULED_HOURS, 0) AS SCHEDULE_VARIANCE_RATE,
    SH.CALCULATED_OVERTIME_HOURS / NULLIF(SH.CALCULATED_ACTUAL_HOURS, 0) AS OVERTIME_RATE,
    SH.CALCULATED_ABSENCE_COUNT / NULLIF(SH.EMPLOYEES_SCHEDULED_COUNT, 0) AS ABSENCE_RATE,
    SH.NO_SHOW_COUNT / NULLIF(SH.EMPLOYEES_SCHEDULED_COUNT, 0) AS NO_SHOW_RATE,
    S.SOURCE_ESTIMATED_SALES / NULLIF(SH.CALCULATED_ACTUAL_HOURS, 0) AS ESTIMATED_SALES_PER_LABOUR_HOUR,
    SH.CALCULATED_LABOUR_COST / NULLIF(S.SOURCE_ESTIMATED_SALES, 0) AS ESTIMATED_LABOUR_COST_RATE,
    SH.CALCULATED_SCHEDULED_HOURS - S.SOURCE_SCHEDULED_HOURS AS SCHEDULED_HOURS_RECONCILIATION_VARIANCE,
    SH.CALCULATED_ACTUAL_HOURS - S.SOURCE_ACTUAL_HOURS AS ACTUAL_HOURS_RECONCILIATION_VARIANCE,
    SH.CALCULATED_LABOUR_COST - S.SOURCE_LABOUR_COST AS LABOUR_COST_RECONCILIATION_VARIANCE,
    CURRENT_TIMESTAMP() AS CREATED_AT
FROM SOURCE_DAILY S
LEFT JOIN SHIFT_DAILY SH
    ON S.WORK_DATE = SH.WORK_DATE
    AND S.RESTAURANT_ID = SH.RESTAURANT_ID