
{{ config(
    materialized = 'table',
    database = 'PORTFOLIO_DB',
    schema = 'MARTS',
    transient = true,
    alias = 'OPS_FACT_EMPLOYEE_SHIFT_PERFORMANCE'
) }}

WITH SOURCE_DATA AS (

    SELECT
        SHIFT_ID,
        TRY_TO_DATE(SHIFT_DATE) AS SHIFT_DATE,
        RESTAURANT_ID,
        EMPLOYEE_ID,
        JOB_ROLE,

        /* THESE COLUMNS ARE ALREADY TIME(9) */
        SCHEDULED_START_TIME,
        SCHEDULED_END_TIME,

        COALESCE(SCHEDULED_HOURS, 0) AS SCHEDULED_HOURS,
        COALESCE(ACTUAL_HOURS, 0) AS ACTUAL_HOURS,
        COALESCE(REGULAR_HOURS, 0) AS REGULAR_HOURS,
        COALESCE(OVERTIME_HOURS, 0) AS OVERTIME_HOURS,
        COALESCE(HOURLY_RATE, 0) AS HOURLY_RATE,
        COALESCE(LABOUR_COST, 0) AS LABOUR_COST,
        COALESCE(ABSENCE_FLAG, FALSE) AS ABSENCE_FLAG,
        COALESCE(NO_SHOW_FLAG, FALSE) AS NO_SHOW_FLAG

    FROM {{ ref('STG_OPS_FACT_EMPLOYEE_SHIFTS') }}

),

CALCULATED AS (

    SELECT
        SHIFT_ID AS SHIFT_PERFORMANCE_KEY,
        SHIFT_ID,
        SHIFT_DATE,
        RESTAURANT_ID,
        EMPLOYEE_ID,
        JOB_ROLE,

        SCHEDULED_START_TIME,
        SCHEDULED_END_TIME,

        SCHEDULED_HOURS,
        ACTUAL_HOURS,
        REGULAR_HOURS,
        OVERTIME_HOURS,
        HOURLY_RATE,
        LABOUR_COST,
        ABSENCE_FLAG,
        NO_SHOW_FLAG,

        ACTUAL_HOURS - SCHEDULED_HOURS
            AS HOURS_VARIANCE,

        ABS(ACTUAL_HOURS - SCHEDULED_HOURS)
            AS ABSOLUTE_HOURS_VARIANCE,

        LEAST(ACTUAL_HOURS, SCHEDULED_HOURS)
            / NULLIF(SCHEDULED_HOURS, 0)
            AS SCHEDULE_ADHERENCE_RATE,

        LEAST(ACTUAL_HOURS, SCHEDULED_HOURS)
            / NULLIF(SCHEDULED_HOURS, 0) * 100
            AS SCHEDULE_ADHERENCE_PERCENTAGE,

        REGULAR_HOURS * HOURLY_RATE
            AS CALCULATED_REGULAR_LABOUR_COST,

        OVERTIME_HOURS * HOURLY_RATE * 1.5
            AS CALCULATED_OVERTIME_LABOUR_COST,

        (
            REGULAR_HOURS * HOURLY_RATE
        ) + (
            OVERTIME_HOURS * HOURLY_RATE * 1.5
        ) AS CALCULATED_TOTAL_LABOUR_COST,

        LABOUR_COST
            - (
                (REGULAR_HOURS * HOURLY_RATE)
                + (OVERTIME_HOURS * HOURLY_RATE * 1.5)
            )
            AS LABOUR_COST_VARIANCE,

        OVERTIME_HOURS
            / NULLIF(ACTUAL_HOURS, 0)
            AS OVERTIME_RATE,

        OVERTIME_HOURS
            / NULLIF(ACTUAL_HOURS, 0) * 100
            AS OVERTIME_PERCENTAGE,

        IFF(
            OVERTIME_HOURS > 0,
            TRUE,
            FALSE
        ) AS OVERTIME_FLAG,

        CASE
            WHEN NO_SHOW_FLAG THEN 'NO_SHOW'
            WHEN ABSENCE_FLAG THEN 'ABSENT'
            WHEN ACTUAL_HOURS = 0 THEN 'DID_NOT_WORK'
            WHEN ACTUAL_HOURS < SCHEDULED_HOURS THEN 'PARTIAL_SHIFT'
            WHEN ACTUAL_HOURS > SCHEDULED_HOURS THEN 'EXTENDED_SHIFT'
            ELSE 'ATTENDED_AS_SCHEDULED'
        END AS ATTENDANCE_STATUS,

        CASE
            WHEN NO_SHOW_FLAG OR ABSENCE_FLAG THEN 0
            WHEN ACTUAL_HOURS > 0 THEN 1
            ELSE 0
        END AS WORKED_SHIFT_FLAG,

        CASE
            WHEN NO_SHOW_FLAG OR ABSENCE_FLAG THEN 1
            ELSE 0
        END AS MISSED_SHIFT_FLAG,

        CURRENT_TIMESTAMP() AS DBT_CREATED_AT

    FROM SOURCE_DATA

)

SELECT *
FROM CALCULATED