{{ config(
    materialized = 'table',
    database = 'PORTFOLIO_DB',
    schema = 'MARTS'
) }}


WITH WASTAGE AS (
    SELECT
        TRY_TO_DATE(EVENT_DATE) AS EVENT_DATE,
        RESTAURANT_ID,
        PRODUCT_ID,
        WASTAGE_REASON,
        COUNT(DISTINCT WASTAGE_EVENT_ID) AS WASTAGE_EVENT_COUNT,
        SUM(COALESCE(WASTAGE_QTY, 0)) AS WASTAGE_QTY,
        SUM(COALESCE(WASTAGE_COST, 0)) AS WASTAGE_COST,
        AVG(COALESCE(UNIT_COST, 0)) AS AVERAGE_UNIT_COST,
        MAX(COALESCE(UNIT_COST, 0)) AS MAX_UNIT_COST,
        MIN(COALESCE(UNIT_COST, 0)) AS MIN_UNIT_COST
    FROM {{ ref('STG_OPS_FACT_WASTAGE_EVENTS') }}
    GROUP BY 1, 2, 3, 4
),
INVENTORY AS (
    SELECT
        TRY_TO_DATE(SNAPSHOT_DATE) AS SNAPSHOT_DATE,
        RESTAURANT_ID,
        PRODUCT_ID,
        SUM(COALESCE(USAGE_QTY, 0)) AS USAGE_QTY,
        SUM(COALESCE(WASTAGE_QTY, 0)) AS INVENTORY_RECORDED_WASTAGE_QTY
    FROM {{ ref('STG_OPS_FACT_INVENTORY_DAILY') }}
    GROUP BY 1, 2, 3
)
SELECT
    MD5(CONCAT_WS('|', W.EVENT_DATE::VARCHAR, W.RESTAURANT_ID, W.PRODUCT_ID, W.WASTAGE_REASON)) AS WASTAGE_DAILY_KEY,
    W.EVENT_DATE,
    W.RESTAURANT_ID,
    W.PRODUCT_ID,
    W.WASTAGE_REASON,
    W.WASTAGE_EVENT_COUNT,
    W.WASTAGE_QTY,
    W.WASTAGE_COST,
    W.AVERAGE_UNIT_COST,
    W.MAX_UNIT_COST,
    W.MIN_UNIT_COST,
    W.WASTAGE_QTY / NULLIF(W.WASTAGE_EVENT_COUNT, 0) AS AVERAGE_QTY_PER_EVENT,
    W.WASTAGE_COST / NULLIF(W.WASTAGE_EVENT_COUNT, 0) AS AVERAGE_COST_PER_EVENT,
    I.USAGE_QTY,
    I.INVENTORY_RECORDED_WASTAGE_QTY,
    W.WASTAGE_QTY / NULLIF(I.USAGE_QTY + W.WASTAGE_QTY, 0) AS WASTAGE_RATE,
    W.WASTAGE_QTY - COALESCE(I.INVENTORY_RECORDED_WASTAGE_QTY, 0) AS WASTAGE_RECONCILIATION_VARIANCE_QTY,
    CURRENT_TIMESTAMP() AS CREATED_AT
FROM WASTAGE W
LEFT JOIN INVENTORY I
    ON W.EVENT_DATE = I.SNAPSHOT_DATE
    AND W.RESTAURANT_ID = I.RESTAURANT_ID
    AND W.PRODUCT_ID = I.PRODUCT_ID