{{ config(
    materialized = 'table',
    transient = true,
    alias = 'OPS_FACT_RESTAURANT_OPERATIONS_DAILY',
    database = 'PORTFOLIO_DB',
    schema = 'MARTS'
) }}

WITH INVENTORY_DAILY AS (

    SELECT
        SNAPSHOT_DATE AS OPERATING_DATE,
        RESTAURANT_ID,

        SUM(OPENING_STOCK_QTY * UNIT_COST)
            AS OPENING_INVENTORY_VALUE,

        SUM(CLOSING_STOCK_QTY * UNIT_COST)
            AS CLOSING_INVENTORY_VALUE,

        SUM(USAGE_QTY * UNIT_COST)
            AS INVENTORY_USAGE_COST,

        SUM(RECEIVED_QTY * UNIT_COST)
            AS INVENTORY_RECEIVED_VALUE,

        SUM(WASTAGE_QTY * UNIT_COST)
            AS INVENTORY_WASTAGE_COST,

        SUM(ADJUSTMENT_QTY * UNIT_COST)
            AS INVENTORY_ADJUSTMENT_VALUE,

        COUNT(DISTINCT PRODUCT_ID)
            AS INVENTORY_PRODUCT_COUNT,

        COUNT(DISTINCT CASE
            WHEN STOCKOUT_FLAG THEN PRODUCT_ID
        END) AS STOCKOUT_PRODUCT_COUNT,

        COUNT(DISTINCT CASE
            WHEN BELOW_REORDER_FLAG THEN PRODUCT_ID
        END) AS BELOW_REORDER_PRODUCT_COUNT

    FROM {{ ref('STG_OPS_FACT_INVENTORY_DAILY') }}

    GROUP BY
        SNAPSHOT_DATE,
        RESTAURANT_ID

),

WASTAGE_DAILY AS (

    SELECT
        EVENT_DATE AS OPERATING_DATE,
        RESTAURANT_ID,

        COUNT(DISTINCT WASTAGE_EVENT_ID)
            AS WASTAGE_EVENT_COUNT,

        COUNT(DISTINCT PRODUCT_ID)
            AS WASTED_PRODUCT_COUNT,

        SUM(WASTAGE_QTY)
            AS WASTAGE_QUANTITY,

        SUM(WASTAGE_COST)
            AS WASTAGE_COST

    FROM {{ ref('STG_OPS_FACT_WASTAGE_EVENTS') }}

    GROUP BY
        EVENT_DATE,
        RESTAURANT_ID

),

DELIVERY_DAILY AS (

    SELECT
        ACTUAL_DELIVERY_DATE AS OPERATING_DATE,
        RESTAURANT_ID,

        COUNT(DISTINCT DELIVERY_ID)
            AS DELIVERY_COUNT,

        COUNT(DISTINCT SUPPLIER_ID)
            AS SUPPLIER_COUNT,

        COUNT(DISTINCT PRODUCT_ID)
            AS DELIVERED_PRODUCT_COUNT,

        SUM(ORDERED_QTY)
            AS ORDERED_QUANTITY,

        SUM(RECEIVED_QTY)
            AS RECEIVED_QUANTITY,

        SUM(ACCEPTED_QTY)
            AS ACCEPTED_QUANTITY,

        SUM(REJECTED_QTY)
            AS REJECTED_QUANTITY,

        AVG(DELIVERY_DELAY_DAYS)
            AS AVERAGE_DELIVERY_DELAY_DAYS,

        AVG(QUALITY_SCORE)
            AS AVERAGE_DELIVERY_QUALITY_SCORE,

        COUNT_IF(ON_TIME_FLAG)
            AS ON_TIME_DELIVERY_COUNT,

        COUNT_IF(IN_FULL_FLAG)
            AS IN_FULL_DELIVERY_COUNT,

        COUNT_IF(OTIF_FLAG)
            AS OTIF_DELIVERY_COUNT

    FROM {{ ref('STG_OPS_FACT_SUPPLIER_DELIVERIES') }}

    WHERE ACTUAL_DELIVERY_DATE IS NOT NULL

    GROUP BY
        ACTUAL_DELIVERY_DATE,
        RESTAURANT_ID

),

LABOUR_DAILY AS (

    SELECT
        WORK_DATE AS OPERATING_DATE,
        RESTAURANT_ID,

        SCHEDULED_HOURS,
        ACTUAL_HOURS,
        REGULAR_HOURS,
        OVERTIME_HOURS,
        LABOUR_COST,
        ABSENCE_COUNT,
        ESTIMATED_SALES,
        LABOUR_COST_PCT_OF_SALES,
        SALES_PER_LABOUR_HOUR

    FROM {{ ref('STG_OPS_FACT_LABOUR_DAILY') }}

),

SHIFT_DAILY AS (

    SELECT
        SHIFT_DATE AS OPERATING_DATE,
        RESTAURANT_ID,

        COUNT(DISTINCT SHIFT_ID)
            AS SCHEDULED_SHIFT_COUNT,

        COUNT(DISTINCT EMPLOYEE_ID)
            AS SCHEDULED_EMPLOYEE_COUNT,

        COUNT(DISTINCT CASE
            WHEN ACTUAL_HOURS > 0
                 AND NOT ABSENCE_FLAG
                 AND NOT NO_SHOW_FLAG
            THEN EMPLOYEE_ID
        END) AS EMPLOYEE_WORKED_COUNT,

        COUNT_IF(ABSENCE_FLAG)
            AS SHIFT_ABSENCE_COUNT,

        COUNT_IF(NO_SHOW_FLAG)
            AS NO_SHOW_COUNT,

        COUNT_IF(OVERTIME_HOURS > 0)
            AS OVERTIME_SHIFT_COUNT

    FROM {{ ref('STG_OPS_FACT_EMPLOYEE_SHIFTS') }}

    GROUP BY
        SHIFT_DATE,
        RESTAURANT_ID

),

DATE_RESTAURANT_SPINE AS (

    SELECT
        OPERATING_DATE,
        RESTAURANT_ID
    FROM INVENTORY_DAILY

    UNION

    SELECT
        OPERATING_DATE,
        RESTAURANT_ID
    FROM WASTAGE_DAILY

    UNION

    SELECT
        OPERATING_DATE,
        RESTAURANT_ID
    FROM DELIVERY_DAILY

    UNION

    SELECT
        OPERATING_DATE,
        RESTAURANT_ID
    FROM LABOUR_DAILY

    UNION

    SELECT
        OPERATING_DATE,
        RESTAURANT_ID
    FROM SHIFT_DAILY

)

SELECT
    SPINE.OPERATING_DATE,
    SPINE.RESTAURANT_ID,

    COALESCE(INVENTORY.OPENING_INVENTORY_VALUE, 0)
        AS OPENING_INVENTORY_VALUE,

    COALESCE(INVENTORY.CLOSING_INVENTORY_VALUE, 0)
        AS CLOSING_INVENTORY_VALUE,

    COALESCE(INVENTORY.INVENTORY_USAGE_COST, 0)
        AS INVENTORY_USAGE_COST,

    COALESCE(INVENTORY.INVENTORY_RECEIVED_VALUE, 0)
        AS INVENTORY_RECEIVED_VALUE,

    COALESCE(INVENTORY.INVENTORY_WASTAGE_COST, 0)
        AS INVENTORY_WASTAGE_COST,

    COALESCE(INVENTORY.INVENTORY_ADJUSTMENT_VALUE, 0)
        AS INVENTORY_ADJUSTMENT_VALUE,

    COALESCE(INVENTORY.INVENTORY_PRODUCT_COUNT, 0)
        AS INVENTORY_PRODUCT_COUNT,

    COALESCE(INVENTORY.STOCKOUT_PRODUCT_COUNT, 0)
        AS STOCKOUT_PRODUCT_COUNT,

    COALESCE(INVENTORY.BELOW_REORDER_PRODUCT_COUNT, 0)
        AS BELOW_REORDER_PRODUCT_COUNT,

    COALESCE(WASTAGE.WASTAGE_EVENT_COUNT, 0)
        AS WASTAGE_EVENT_COUNT,

    COALESCE(WASTAGE.WASTED_PRODUCT_COUNT, 0)
        AS WASTED_PRODUCT_COUNT,

    COALESCE(WASTAGE.WASTAGE_QUANTITY, 0)
        AS WASTAGE_QUANTITY,

    COALESCE(WASTAGE.WASTAGE_COST, 0)
        AS WASTAGE_COST,

    COALESCE(DELIVERY.DELIVERY_COUNT, 0)
        AS DELIVERY_COUNT,

    COALESCE(DELIVERY.SUPPLIER_COUNT, 0)
        AS SUPPLIER_COUNT,

    COALESCE(DELIVERY.DELIVERED_PRODUCT_COUNT, 0)
        AS DELIVERED_PRODUCT_COUNT,

    COALESCE(DELIVERY.ORDERED_QUANTITY, 0)
        AS ORDERED_QUANTITY,

    COALESCE(DELIVERY.RECEIVED_QUANTITY, 0)
        AS RECEIVED_QUANTITY,

    COALESCE(DELIVERY.ACCEPTED_QUANTITY, 0)
        AS ACCEPTED_QUANTITY,

    COALESCE(DELIVERY.REJECTED_QUANTITY, 0)
        AS REJECTED_QUANTITY,

    DELIVERY.AVERAGE_DELIVERY_DELAY_DAYS,
    DELIVERY.AVERAGE_DELIVERY_QUALITY_SCORE,

    COALESCE(DELIVERY.ON_TIME_DELIVERY_COUNT, 0)
        AS ON_TIME_DELIVERY_COUNT,

    COALESCE(DELIVERY.IN_FULL_DELIVERY_COUNT, 0)
        AS IN_FULL_DELIVERY_COUNT,

    COALESCE(DELIVERY.OTIF_DELIVERY_COUNT, 0)
        AS OTIF_DELIVERY_COUNT,

    DELIVERY.ON_TIME_DELIVERY_COUNT
        / NULLIF(DELIVERY.DELIVERY_COUNT, 0)
        AS ON_TIME_DELIVERY_RATE,

    DELIVERY.IN_FULL_DELIVERY_COUNT
        / NULLIF(DELIVERY.DELIVERY_COUNT, 0)
        AS IN_FULL_DELIVERY_RATE,

    DELIVERY.OTIF_DELIVERY_COUNT
        / NULLIF(DELIVERY.DELIVERY_COUNT, 0)
        AS OTIF_RATE,

    COALESCE(LABOUR.SCHEDULED_HOURS, 0)
        AS SCHEDULED_HOURS,

    COALESCE(LABOUR.ACTUAL_HOURS, 0)
        AS ACTUAL_HOURS,

    COALESCE(LABOUR.REGULAR_HOURS, 0)
        AS REGULAR_HOURS,

    COALESCE(LABOUR.OVERTIME_HOURS, 0)
        AS OVERTIME_HOURS,

    COALESCE(LABOUR.LABOUR_COST, 0)
        AS LABOUR_COST,

    COALESCE(LABOUR.ABSENCE_COUNT, 0)
        AS ABSENCE_COUNT,

    COALESCE(LABOUR.ESTIMATED_SALES, 0)
        AS ESTIMATED_SALES,

    LABOUR.LABOUR_COST_PCT_OF_SALES,
    LABOUR.SALES_PER_LABOUR_HOUR,

    COALESCE(SHIFT.SCHEDULED_SHIFT_COUNT, 0)
        AS SCHEDULED_SHIFT_COUNT,

    COALESCE(SHIFT.SCHEDULED_EMPLOYEE_COUNT, 0)
        AS SCHEDULED_EMPLOYEE_COUNT,

    COALESCE(SHIFT.EMPLOYEE_WORKED_COUNT, 0)
        AS EMPLOYEE_WORKED_COUNT,

    COALESCE(SHIFT.SHIFT_ABSENCE_COUNT, 0)
        AS SHIFT_ABSENCE_COUNT,

    COALESCE(SHIFT.NO_SHOW_COUNT, 0)
        AS NO_SHOW_COUNT,

    COALESCE(SHIFT.OVERTIME_SHIFT_COUNT, 0)
        AS OVERTIME_SHIFT_COUNT,

    LABOUR.LABOUR_COST
        / NULLIF(LABOUR.ESTIMATED_SALES, 0)
        AS CALCULATED_LABOUR_COST_RATE,

    LABOUR.LABOUR_COST
        / NULLIF(LABOUR.ESTIMATED_SALES, 0) * 100
        AS CALCULATED_LABOUR_COST_PERCENTAGE,

    LABOUR.ESTIMATED_SALES
        / NULLIF(LABOUR.ACTUAL_HOURS, 0)
        AS CALCULATED_SALES_PER_LABOUR_HOUR,

    INVENTORY.INVENTORY_USAGE_COST
        / NULLIF(LABOUR.ESTIMATED_SALES, 0)
        AS INVENTORY_USAGE_COST_RATE,

    WASTAGE.WASTAGE_COST
        / NULLIF(LABOUR.ESTIMATED_SALES, 0)
        AS WASTAGE_COST_RATE,

    COALESCE(INVENTORY.INVENTORY_USAGE_COST, 0)
        + COALESCE(LABOUR.LABOUR_COST, 0)
        AS ESTIMATED_PRIME_COST,

    (
        COALESCE(INVENTORY.INVENTORY_USAGE_COST, 0)
        + COALESCE(LABOUR.LABOUR_COST, 0)
    ) / NULLIF(LABOUR.ESTIMATED_SALES, 0)
        AS ESTIMATED_PRIME_COST_RATE,

    COALESCE(LABOUR.ESTIMATED_SALES, 0)
        - COALESCE(INVENTORY.INVENTORY_USAGE_COST, 0)
        - COALESCE(WASTAGE.WASTAGE_COST, 0)
        - COALESCE(LABOUR.LABOUR_COST, 0)
        AS ESTIMATED_CONTRIBUTION_AFTER_LABOUR,

    CURRENT_TIMESTAMP() AS DBT_CREATED_AT

FROM DATE_RESTAURANT_SPINE AS SPINE

LEFT JOIN INVENTORY_DAILY AS INVENTORY
    ON SPINE.OPERATING_DATE = INVENTORY.OPERATING_DATE
    AND SPINE.RESTAURANT_ID = INVENTORY.RESTAURANT_ID

LEFT JOIN WASTAGE_DAILY AS WASTAGE
    ON SPINE.OPERATING_DATE = WASTAGE.OPERATING_DATE
    AND SPINE.RESTAURANT_ID = WASTAGE.RESTAURANT_ID

LEFT JOIN DELIVERY_DAILY AS DELIVERY
    ON SPINE.OPERATING_DATE = DELIVERY.OPERATING_DATE
    AND SPINE.RESTAURANT_ID = DELIVERY.RESTAURANT_ID

LEFT JOIN LABOUR_DAILY AS LABOUR
    ON SPINE.OPERATING_DATE = LABOUR.OPERATING_DATE
    AND SPINE.RESTAURANT_ID = LABOUR.RESTAURANT_ID

LEFT JOIN SHIFT_DAILY AS SHIFT
    ON SPINE.OPERATING_DATE = SHIFT.OPERATING_DATE
    AND SPINE.RESTAURANT_ID = SHIFT.RESTAURANT_ID