-- Monthly supplier scorecard aggregation with weighted performance scoring
-- Co-authored with CoCo
{{ config(
    materialized = 'table',
    database = 'PORTFOLIO_DB',
    schema = 'MARTS'
) }}

WITH MONTHLY AS (
    SELECT
        DATE_TRUNC('MONTH', ACTUAL_DELIVERY_DATE) AS DELIVERY_MONTH,
        SUPPLIER_ID,
        COUNT(DISTINCT PURCHASE_ORDER_ID) AS PURCHASE_ORDER_COUNT,
        COUNT(DISTINCT DELIVERY_ID) AS DELIVERY_COUNT,
        SUM(ORDERED_QTY) AS TOTAL_ORDERED_QTY,
        SUM(RECEIVED_QTY) AS TOTAL_RECEIVED_QTY,
        SUM(ACCEPTED_QTY) AS TOTAL_ACCEPTED_QTY,
        SUM(REJECTED_QTY) AS TOTAL_REJECTED_QTY,
        SUM(CALCULATED_ORDER_VALUE) AS TOTAL_ORDER_VALUE,
        SUM(RECEIVED_VALUE) AS TOTAL_RECEIVED_VALUE,
        SUM(ACCEPTED_VALUE) AS TOTAL_ACCEPTED_VALUE,
        SUM(REJECTED_VALUE) AS TOTAL_REJECTED_VALUE,
        SUM(SHORT_DELIVERY_VALUE) AS TOTAL_SHORT_DELIVERY_VALUE,
        AVG(IFF(ON_TIME_FLAG, 1, 0)) AS ON_TIME_DELIVERY_RATE,
        AVG(IFF(IN_FULL_FLAG, 1, 0)) AS IN_FULL_DELIVERY_RATE,
        AVG(IFF(OTIF_FLAG, 1, 0)) AS OTIF_RATE,
        SUM(RECEIVED_QTY) / NULLIF(SUM(ORDERED_QTY), 0) AS FILL_RATE,
        SUM(ACCEPTED_QTY) / NULLIF(SUM(RECEIVED_QTY), 0) AS ACCEPTANCE_RATE,
        SUM(REJECTED_QTY) / NULLIF(SUM(RECEIVED_QTY), 0) AS REJECTION_RATE,
        AVG(DELIVERY_DELAY_DAYS) AS AVERAGE_DELIVERY_DELAY_DAYS,
        AVG(ACTUAL_LEAD_TIME_DAYS) AS AVERAGE_ACTUAL_LEAD_TIME_DAYS,
        AVG(QUALITY_SCORE) AS AVERAGE_QUALITY_SCORE
    FROM {{ ref('OPS_FACT_SUPPLIER_DELIVERY_PERFORMANCE') }}
    GROUP BY 1, 2
)
SELECT
    MD5(CONCAT_WS('|', DELIVERY_MONTH::VARCHAR, SUPPLIER_ID)) AS SUPPLIER_SCORECARD_KEY,
    DELIVERY_MONTH,
    SUPPLIER_ID,
    PURCHASE_ORDER_COUNT,
    DELIVERY_COUNT,
    TOTAL_ORDERED_QTY,
    TOTAL_RECEIVED_QTY,
    TOTAL_ACCEPTED_QTY,
    TOTAL_REJECTED_QTY,
    TOTAL_ORDER_VALUE,
    TOTAL_RECEIVED_VALUE,
    TOTAL_ACCEPTED_VALUE,
    TOTAL_REJECTED_VALUE,
    TOTAL_SHORT_DELIVERY_VALUE,
    ON_TIME_DELIVERY_RATE,
    IN_FULL_DELIVERY_RATE,
    OTIF_RATE,
    FILL_RATE,
    ACCEPTANCE_RATE,
    REJECTION_RATE,
    AVERAGE_DELIVERY_DELAY_DAYS,
    AVERAGE_ACTUAL_LEAD_TIME_DAYS,
    AVERAGE_QUALITY_SCORE,
    (
        OTIF_RATE * 0.40
        + LEAST(FILL_RATE, 1) * 0.25
        + LEAST(ACCEPTANCE_RATE, 1) * 0.20
        + LEAST(AVERAGE_QUALITY_SCORE / 5.0, 1) * 0.15
    ) * 100 AS SUPPLIER_PERFORMANCE_SCORE,
    CURRENT_TIMESTAMP() AS CREATED_AT
FROM MONTHLY