-- ROYCE: I HAVE A PRE-SET-UP AWS THAT I USE FOR DATA TRAINING. I AM MAKING AN INTEGRATION HERE TO CONNECT FROM MY AWS TO SNOWFLAKE

--STORAGE INTEGRATION CREATION
-- CREATE OR REPLACE STORAGE INTEGRATION PORTFOLIO_S3_INTEGRATION
--     TYPE = EXTERNAL_STAGE
--     STORAGE_PROVIDER = 'S3'
--     ENABLED = TRUE
--     STORAGE_AWS_ROLE_ARN = <'ROYCE 17/07: REMOVING MY ARN HERE FOR NOW'>
--     STORAGE_ALLOWED_LOCATIONS =
--         ('s3://rawdataroycefortraining/');


-- DESC INTEGRATION PORTFOLIO_S3_INTEGRATION;