SELECT TOP 10 
PD.STORE_ID,
PD.TRANSACTION_DATE,
PD.TRANSACTION_TIME_BINNED_30 AS TRANSACTION_TIME,
PD.SALES_CHANNEL,
PD.SALES_TYPE,
PD.MEMBER_ID,
SUM(PD.AMOUNT_GROSS) AS AMOUNT_GROSS,
SUM(PD.AMOUNT_GST) AS AMOUNT_GST,
SUM(PD.AMOUNT_NET) AS AMOUNT_NET
FROM PORTFOLIO_DB.STAGING.STG_PRODUCT_DATA PD

GROUP BY
PD.STORE_ID,
PD.TRANSACTION_DATE,
PD.TRANSACTION_TIME_BINNED_30,
PD.SALES_CHANNEL,
PD.SALES_TYPE,
PD.MEMBER_ID