



USE SCHEMA PORTFOLIO_DB.MARTS;
USE ROLE ROYCE_DEV;

CREATE OR REPLACE STAGE PORTFOLIO_DB.MARTS.EXPORT_STAGE
    DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'Stage for exporting marts tables and views';

--------------------------------------------------------------------
--------------------------------------------------------------------
COPY INTO @PORTFOLIO_DB.MARTS.EXPORT_STAGE/big_fact_table_parquet/AWS_FACT_PRODUCT_INSTANCE
FROM (
    SELECT *
    FROM PORTFOLIO_DB.MARTS.AWS_FACT_PRODUCT_INSTANCE
    WHERE TRANSACTION_DATE >= '2025-11-01'
)
FILE_FORMAT = (TYPE = PARQUET)
SINGLE = FALSE
MAX_FILE_SIZE = 99614720
HEADER = TRUE
OVERWRITE = TRUE;

COPY INTO @PORTFOLIO_DB.MARTS.EXPORT_STAGE/big_fact_table_parquet/AWS_FACT_PRODUCT_MODIFIER
FROM (
    SELECT *
    FROM PORTFOLIO_DB.MARTS.AWS_FACT_PRODUCT_MODIFIER
    WHERE TRANSACTION_DATE >= '2025-11-01'
)
FILE_FORMAT = (TYPE = PARQUET)
SINGLE = FALSE
MAX_FILE_SIZE = 99614720
HEADER = TRUE
OVERWRITE = TRUE;
--------------------------------------------------------------------
--------------------------------------------------------------------
COPY INTO @PORTFOLIO_DB.MARTS.EXPORT_STAGE/big_fact_tables/AWS_FACT_STATS_SUMMARY
FROM PORTFOLIO_DB.MARTS.AWS_FACT_STATS_SUMMARY
FILE_FORMAT = (TYPE = CSV, COMPRESSION = NONE, FIELD_OPTIONALLY_ENCLOSED_BY = '"')
SINGLE = FALSE
MAX_FILE_SIZE = 99614720
HEADER = TRUE
OVERWRITE = TRUE;

COPY INTO @PORTFOLIO_DB.MARTS.EXPORT_STAGE/csv/OPS_AGG_SUPPLIER_SCORE_CARD_MONTHLY
FROM PORTFOLIO_DB.MARTS.OPS_AGG_SUPPLIER_SCORE_CARD_MONTHLY
FILE_FORMAT = (TYPE = CSV, COMPRESSION = NONE, FIELD_OPTIONALLY_ENCLOSED_BY = '"')
SINGLE = TRUE
MAX_FILE_SIZE = 5368709120
HEADER = TRUE
OVERWRITE = TRUE;

COPY INTO @PORTFOLIO_DB.MARTS.EXPORT_STAGE/csv/OPS_FACT_EMPLOYEE_SHIFT_PERFORMANCE
FROM PORTFOLIO_DB.MARTS.OPS_FACT_EMPLOYEE_SHIFT_PERFORMANCE
FILE_FORMAT = (TYPE = CSV, COMPRESSION = NONE, FIELD_OPTIONALLY_ENCLOSED_BY = '"')
SINGLE = TRUE
MAX_FILE_SIZE = 5368709120
HEADER = TRUE
OVERWRITE = TRUE;

COPY INTO @PORTFOLIO_DB.MARTS.EXPORT_STAGE/csv/OPS_FACT_INVENTORY_PERFORMANCE_DAILY
FROM PORTFOLIO_DB.MARTS.OPS_FACT_INVENTORY_PERFORMANCE_DAILY
FILE_FORMAT = (TYPE = CSV, COMPRESSION = NONE, FIELD_OPTIONALLY_ENCLOSED_BY = '"')
SINGLE = TRUE
MAX_FILE_SIZE = 5368709120
HEADER = TRUE
OVERWRITE = TRUE;

COPY INTO @PORTFOLIO_DB.MARTS.EXPORT_STAGE/csv/OPS_FACT_INVENTORY_WASTAGE_DAILY
FROM PORTFOLIO_DB.MARTS.OPS_FACT_INVENTORY_WASTAGE_DAILY
FILE_FORMAT = (TYPE = CSV, COMPRESSION = NONE, FIELD_OPTIONALLY_ENCLOSED_BY = '"')
SINGLE = TRUE
MAX_FILE_SIZE = 5368709120
HEADER = TRUE
OVERWRITE = TRUE;

COPY INTO @PORTFOLIO_DB.MARTS.EXPORT_STAGE/csv/OPS_FACT_RESTAURANT_LABOUR_PERFORMANCE
FROM PORTFOLIO_DB.MARTS.OPS_FACT_RESTAURANT_LABOUR_PERFORMANCE
FILE_FORMAT = (TYPE = CSV, COMPRESSION = NONE, FIELD_OPTIONALLY_ENCLOSED_BY = '"')
SINGLE = TRUE
MAX_FILE_SIZE = 5368709120
HEADER = TRUE
OVERWRITE = TRUE;

COPY INTO @PORTFOLIO_DB.MARTS.EXPORT_STAGE/csv/OPS_FACT_RESTAURANT_OPERATIONS_DAILY
FROM PORTFOLIO_DB.MARTS.OPS_FACT_RESTAURANT_OPERATIONS_DAILY
FILE_FORMAT = (TYPE = CSV, COMPRESSION = NONE, FIELD_OPTIONALLY_ENCLOSED_BY = '"')
SINGLE = TRUE
HEADER = TRUE
OVERWRITE = TRUE;

COPY INTO @PORTFOLIO_DB.MARTS.EXPORT_STAGE/csv/OPS_FACT_SUPPLIER_DELIVERY_PERFORMANCE
FROM PORTFOLIO_DB.MARTS.OPS_FACT_SUPPLIER_DELIVERY_PERFORMANCE
FILE_FORMAT = (TYPE = CSV, COMPRESSION = NONE, FIELD_OPTIONALLY_ENCLOSED_BY = '"')
SINGLE = TRUE
HEADER = TRUE
OVERWRITE = TRUE;

--------------------------------------------------------------------
--EXPORTNG FOR VIEWSS
--------------------------------------------------------------------
COPY INTO @PORTFOLIO_DB.MARTS.EXPORT_STAGE/csv_views/V_DIM_DATE
FROM PORTFOLIO_DB.MARTS.V_DIM_DATE
FILE_FORMAT = (TYPE = CSV, COMPRESSION = NONE, FIELD_OPTIONALLY_ENCLOSED_BY = '"')
SINGLE = TRUE
HEADER = TRUE
OVERWRITE = TRUE;

COPY INTO @PORTFOLIO_DB.MARTS.EXPORT_STAGE/csv_views/V_DIM_MEMBER_PROFILE
FROM PORTFOLIO_DB.MARTS.V_DIM_MEMBER_PROFILE
FILE_FORMAT = (TYPE = CSV, COMPRESSION = NONE, FIELD_OPTIONALLY_ENCLOSED_BY = '"')
SINGLE = TRUE
MAX_FILE_SIZE = 5368709120
HEADER = TRUE
OVERWRITE = TRUE;

COPY INTO @PORTFOLIO_DB.MARTS.EXPORT_STAGE/csv_views/V_DIM_PRODUCT_CODE
FROM PORTFOLIO_DB.MARTS.V_DIM_PRODUCT_CODE
FILE_FORMAT = (TYPE = CSV, COMPRESSION = NONE, FIELD_OPTIONALLY_ENCLOSED_BY = '"')
SINGLE = TRUE
HEADER = TRUE
OVERWRITE = TRUE;

COPY INTO @PORTFOLIO_DB.MARTS.EXPORT_STAGE/csv_views/V_DIM_PRODUCT_CODE_CHILD
FROM PORTFOLIO_DB.MARTS.V_DIM_PRODUCT_CODE_CHILD
FILE_FORMAT = (TYPE = CSV, COMPRESSION = NONE, FIELD_OPTIONALLY_ENCLOSED_BY = '"')
SINGLE = TRUE
HEADER = TRUE
OVERWRITE = TRUE;

COPY INTO @PORTFOLIO_DB.MARTS.EXPORT_STAGE/csv_views/V_DIM_RESTAURANTS
FROM PORTFOLIO_DB.MARTS.V_DIM_RESTAURANTS
FILE_FORMAT = (TYPE = CSV, COMPRESSION = NONE, FIELD_OPTIONALLY_ENCLOSED_BY = '"')
SINGLE = TRUE
HEADER = TRUE
OVERWRITE = TRUE;

COPY INTO @PORTFOLIO_DB.MARTS.EXPORT_STAGE/csv_views/V_DIM_SALES_CHANNEL
FROM PORTFOLIO_DB.MARTS.V_DIM_SALES_CHANNEL
FILE_FORMAT = (TYPE = CSV, COMPRESSION = NONE, FIELD_OPTIONALLY_ENCLOSED_BY = '"')
SINGLE = TRUE
HEADER = TRUE
OVERWRITE = TRUE;

COPY INTO @PORTFOLIO_DB.MARTS.EXPORT_STAGE/csv_views/V_DIM_SALES_TYPE
FROM PORTFOLIO_DB.MARTS.V_DIM_SALES_TYPE
FILE_FORMAT = (TYPE = CSV, COMPRESSION = NONE, FIELD_OPTIONALLY_ENCLOSED_BY = '"')
SINGLE = TRUE
HEADER = TRUE
OVERWRITE = TRUE;

COPY INTO @PORTFOLIO_DB.MARTS.EXPORT_STAGE/csv_views/V_DIM_TIME
FROM PORTFOLIO_DB.MARTS.V_DIM_TIME
FILE_FORMAT = (TYPE = CSV, COMPRESSION = NONE, FIELD_OPTIONALLY_ENCLOSED_BY = '"')
SINGLE = TRUE
HEADER = TRUE
OVERWRITE = TRUE;

COPY INTO @PORTFOLIO_DB.MARTS.EXPORT_STAGE/csv_views/V_OPS_DIM_EMPLOYEES
FROM PORTFOLIO_DB.MARTS.V_OPS_DIM_EMPLOYEES
FILE_FORMAT = (TYPE = CSV, COMPRESSION = NONE, FIELD_OPTIONALLY_ENCLOSED_BY = '"')
SINGLE = TRUE
HEADER = TRUE
OVERWRITE = TRUE;

COPY INTO @PORTFOLIO_DB.MARTS.EXPORT_STAGE/csv_views/V_OPS_DIM_SUPPLIERS
FROM PORTFOLIO_DB.MARTS.V_OPS_DIM_SUPPLIERS
FILE_FORMAT = (TYPE = CSV, COMPRESSION = NONE, FIELD_OPTIONALLY_ENCLOSED_BY = '"')
SINGLE = TRUE
HEADER = TRUE
OVERWRITE = TRUE;
