--CSV
CREATE OR REPLACE FILE FORMAT PORTFOLIO_DB_RAW.RAW.CSV_FORMAT
    TYPE = CSV
    PARSE_HEADER = TRUE
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    TRIM_SPACE = TRUE
    EMPTY_FIELD_AS_NULL = TRUE
    NULL_IF = ('', 'NULL', 'null')
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;


--PARQUET
CREATE OR REPLACE FILE FORMAT PORTFOLIO_DB_RAW.RAW.PARQUET_FORMAT
    TYPE = PARQUET;