USE ROLE ROYCE_DATA_INGESTOR;

CREATE OR REPLACE TABLE PORTFOLIO_DB_RAW.RAW.AWS_ROYCE_PRODUCT_ITEMS
USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(
        INFER_SCHEMA(
            LOCATION =>
                '@PORTFOLIO_DB_RAW.RAW.S3_RAW_STAGE/References/Products/PRODUCT_ITEMS_CREATIVE.csv',
            FILE_FORMAT =>
                'PORTFOLIO_DB_RAW.RAW.CSV_FORMAT'
        )
    )
);

COPY INTO PORTFOLIO_DB_RAW.RAW.AWS_ROYCE_PRODUCT_ITEMS
FROM @PORTFOLIO_DB_RAW.RAW.S3_RAW_STAGE/References/Products/
FILE_FORMAT = (
    FORMAT_NAME = 'PORTFOLIO_DB_RAW.RAW.CSV_FORMAT'
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
PATTERN = '.*PRODUCT_ITEMS_CREATIVE[.]csv'
ON_ERROR = 'ABORT_STATEMENT';