USE ROLE ROYCE_DATA_INGESTOR;

CREATE OR REPLACE TABLE PORTFOLIO_DB_RAW.RAW.AWS_ROYCE_SAMPLE_MEMBERS
USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(
        INFER_SCHEMA(
            LOCATION =>
                '@PORTFOLIO_DB_RAW.RAW.S3_RAW_STAGE/References/Members/SAMPLE_MEMS_WITH_NAMES.csv',
            FILE_FORMAT =>
                'PORTFOLIO_DB_RAW.RAW.CSV_FORMAT'
        )
    )
);

COPY INTO PORTFOLIO_DB_RAW.RAW.AWS_ROYCE_SAMPLE_MEMBERS
FROM @PORTFOLIO_DB_RAW.RAW.S3_RAW_STAGE/References/Members/
FILE_FORMAT = (
    FORMAT_NAME = 'PORTFOLIO_DB_RAW.RAW.CSV_FORMAT'
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
PATTERN = '.*SAMPLE_MEMS_WITH_NAMES[.]csv'
ON_ERROR = 'ABORT_STATEMENT';