USE ROLE ROYCE_DATA_INGESTOR;

CREATE OR REPLACE TABLE PORTFOLIO_DB_RAW.RAW.AWS_ROYCE_UNI_AU_HOLIDAYS
USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(
        INFER_SCHEMA(
            LOCATION =>
                '@PORTFOLIO_DB_RAW.RAW.S3_RAW_STAGE/References/Date_Time_Dimension/UNI_AU_HOLIDAYS.csv',
            FILE_FORMAT =>
                'PORTFOLIO_DB_RAW.RAW.CSV_FORMAT'
        )
    )
);

COPY INTO PORTFOLIO_DB_RAW.RAW.AWS_ROYCE_UNI_AU_HOLIDAYS
FROM @PORTFOLIO_DB_RAW.RAW.S3_RAW_STAGE/References/Date_Time_Dimension/
FILE_FORMAT = (
    FORMAT_NAME = 'PORTFOLIO_DB_RAW.RAW.CSV_FORMAT'
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
PATTERN = '.*UNI_AU_HOLIDAYS[.]csv'
ON_ERROR = 'ABORT_STATEMENT';