
USE DATABASE PORTFOLIO_DB_RAW;
USE SCHEMA RAW;

CREATE OR REPLACE STAGE S3_RAW_STAGE
    URL = 's3://rawdataroycefortraining/'
    STORAGE_INTEGRATION = PORTFOLIO_S3_INTEGRATION;


--CHECKING
LIST @S3_RAW_STAGE;