
//I CREATED A TABLE FIRST, SETTING UP WHERE THE DATA IS COMING FROM AND WHAT FORMAT TO USE.
CREATE OR REPLACE TABLE PORTFOLIO_DB_RAW.RAW.AWS_ROYCE_PRODUCTS_DATA
USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(
        INFER_SCHEMA(
            LOCATION =>
                '@PORTFOLIO_DB_RAW.RAW.S3_RAW_STAGE/Rawdata/Products_and_sales/PRODUCTS_DATA_FOR_PLAYGROUND_ROYCE.parquet',
            FILE_FORMAT =>
                'PORTFOLIO_DB_RAW.RAW.PARQUET_FORMAT'
        )
    )
);

//DATA LOADING VIA COPY INTO
COPY INTO PORTFOLIO_DB_RAW.RAW.AWS_ROYCE_PRODUCTS_DATA
FROM @PORTFOLIO_DB_RAW.RAW.S3_RAW_STAGE/Rawdata/Products_and_sales/
FILE_FORMAT = (
    FORMAT_NAME = 'PORTFOLIO_DB_RAW.RAW.PARQUET_FORMAT'
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
PATTERN = '.*PRODUCTS_DATA_FOR_PLAYGROUND_ROYCE[.]parquet'
ON_ERROR = 'ABORT_STATEMENT';