

CREATE OR REPLACE TABLE PORTFOLIO_DB_RAW.RAW.AWS_ROYCE_RESTAURANT_REVIEWS
USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(
        INFER_SCHEMA(
            LOCATION =>
                '@PORTFOLIO_DB_RAW.RAW.S3_RAW_STAGE/Rawdata/Reviews/Restaurant_Reviews.csv',
            FILE_FORMAT =>
                'PORTFOLIO_DB_RAW.RAW.CSV_FORMAT'
        )
    )
);


COPY INTO PORTFOLIO_DB_RAW.RAW.AWS_ROYCE_RESTAURANT_REVIEWS
FROM @PORTFOLIO_DB_RAW.RAW.S3_RAW_STAGE/Rawdata/Reviews/
FILE_FORMAT = (
    FORMAT_NAME = 'PORTFOLIO_DB_RAW.RAW.CSV_FORMAT'
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
PATTERN = '.*Restaurant_Reviews[.]csv'
ON_ERROR = 'ABORT_STATEMENT';



SELECT *
FROM PORTFOLIO_DB_RAW.RAW.AWS_ROYCE_RESTAURANT_REVIEWS
LIMIT 20