--ROYCE 17/07: WH, DB, AND SCHEMA CREATION.

-- CREATE WAREHOUSE ROYCE_WH;
-- CREATE DATABASE PORTFOLIO_DB;
-- CREATE DATABASE PORTFOLIO_DB_RAW;
-- CREATE SCHEMA PORTFOLIO_DB_RAW.RAW;
-- CREATE SCHEMA PORTFOLIO_DB.STAGING;
-- CREATE SCHEMA PORTFOLIO_DB.MARTS;
-- CREATE SCHEMA PORTFOLIO_DB.SEMANTIC;

-- USE ROLE USERADMIN;
-- CREATE ROLE ROYCE_DEV
--     COMMENT = 'Role for development';

-- USE ROLE SECURITYADMIN;
-- GRANT ROLE ROYCE_DEV TO ROLE SYSADMIN;

-- GRANT USAGE ON WAREHOUSE ROYCE_WH TO ROLE ROYCE_DEV;
-- GRANT ALL PRIVILEGES ON DATABASE PORTFOLIO_DB_RAW TO ROLE ROYCE_DEV;
-- GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE PORTFOLIO_DB_RAW TO ROLE ROYCE_DEV;
-- GRANT CREATE TABLE ON ALL SCHEMAS IN DATABASE PORTFOLIO_DB_RAW TO ROLE ROYCE_DEV;
-- GRANT CREATE VIEW ON ALL SCHEMAS IN DATABASE PORTFOLIO_DB_RAW TO ROLE ROYCE_DEV;



-- CREATE ROLE ROYCE_DATA_INGESTOR;

-- GRANT USAGE ON DATABASE PORTFOLIO_DB_RAW
-- TO ROLE ROYCE_DATA_INGESTOR;

-- GRANT USAGE ON SCHEMA PORTFOLIO_DB_RAW.RAW
-- TO ROLE ROYCE_DATA_INGESTOR;

-- GRANT CREATE TABLE,
--       CREATE STAGE,
--       CREATE FILE FORMAT
-- ON SCHEMA PORTFOLIO_DB_RAW.RAW
-- TO ROLE ROYCE_DATA_INGESTOR;

-- GRANT ROLE ROYCE_DATA_INGESTOR TO ROLE SYSADMIN;