-- USE ROLE SYSADMIN;

-- CREATE WAREHOUSE IF NOT EXISTS MCP_EXTERNAL_WH
--     WAREHOUSE_SIZE = 'XSMALL'
--     AUTO_SUSPEND = 60
--     AUTO_RESUME = TRUE
--     INITIALLY_SUSPENDED = TRUE
--     COMMENT = 'RESTRICTED WAREHOUSE FOR EXTERNAL MCP USERS';



-- CREATE USER IF NOT EXISTS ROYCE_TEST_USER
--     TYPE = PERSON
--     LOGIN_NAME = 'ROYCE_TEST_USER'
--     PASSWORD = 'SuperPassword123!'
--     MUST_CHANGE_PASSWORD = FALSE
--     DEFAULT_ROLE = MCP_PUBLIC_ROLE
--     DEFAULT_WAREHOUSE = MCP_EXTERNAL_WH
--     DEFAULT_NAMESPACE = PORTFOLIO_DB.SEMANTIC
--     DEFAULT_SECONDARY_ROLES = ()
--     COMMENT = 'GENERIC LOGIN USER FOR CLAUDE MCP OAUTH';




USE ROLE ACCOUNTADMIN;

-- DATABASE AND SCHEMA
GRANT USAGE
ON DATABASE PORTFOLIO_DB
TO ROLE MCP_PUBLIC_ROLE;

GRANT USAGE
ON SCHEMA PORTFOLIO_DB.SEMANTIC
TO ROLE MCP_PUBLIC_ROLE;

-- SEMANTIC VIEW
GRANT REFERENCES
ON SEMANTIC VIEW PORTFOLIO_DB.SEMANTIC.SV_EXECUTIVE_SUMMARY
TO ROLE MCP_PUBLIC_ROLE;

GRANT SELECT
ON SEMANTIC VIEW PORTFOLIO_DB.SEMANTIC.SV_EXECUTIVE_SUMMARY
TO ROLE MCP_PUBLIC_ROLE;

-- MCP SERVER
GRANT USAGE
ON MCP SERVER PORTFOLIO_DB.PUBLIC.PORTFOLIO_ROYCE_TABORA_MCP_SERVER
TO ROLE MCP_PUBLIC_ROLE;

-- USER ROLE
GRANT ROLE MCP_PUBLIC_ROLE
TO USER ROYCE_TEST_USER;



GRANT USAGE
ON SCHEMA PORTFOLIO_DB.MARTS
TO ROLE MCP_PUBLIC_ROLE;

GRANT SELECT
ON ALL TABLES IN SCHEMA PORTFOLIO_DB.MARTS
TO ROLE MCP_PUBLIC_ROLE;

GRANT SELECT
ON ALL VIEWS IN SCHEMA PORTFOLIO_DB.MARTS
TO ROLE MCP_PUBLIC_ROLE;