USE ROLE ROYCE_DATA_INGESTOR;

CREATE OR REPLACE TABLE PORTFOLIO_DB_RAW.RAW.OPS_DIM_EMPLOYEES
USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(
        INFER_SCHEMA(
            LOCATION => '@"PORTFOLIO_DB_RAW"."RAW"."CSV_LOAD_STAGE"/DIM_EMPLOYEES.csv',
            FILE_FORMAT => 'PORTFOLIO_DB_RAW.RAW.CSV_FORMAT'
        )
    )
);



COPY INTO PORTFOLIO_DB_RAW.RAW.OPS_DIM_EMPLOYEES
FROM @PORTFOLIO_DB_RAW.RAW.CSV_LOAD_STAGE
FILES = ('DIM_EMPLOYEES.csv')
FILE_FORMAT = (
    FORMAT_NAME = PORTFOLIO_DB_RAW.RAW.CSV_FORMAT
)
MATCH_BY_COLUMN_NAME = 'CASE_INSENSITIVE'
ON_ERROR = 'ABORT_STATEMENT';