-- Load OPS_FACT_INVENTORY_DAILY from CSV stage with schema inference and column matching
-- Co-authored with CoCo
USE ROLE ROYCE_DATA_INGESTOR;

CREATE OR REPLACE TABLE PORTFOLIO_DB_RAW.RAW.OPS_FACT_INVENTORY_DAILY
USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(
        INFER_SCHEMA(
            LOCATION => '@PORTFOLIO_DB_RAW.RAW.CSV_LOAD_STAGE/FACT_INVENTORY_DAILY.csv',
            FILE_FORMAT => 'PORTFOLIO_DB_RAW.RAW.CSV_FORMAT'
        )
    )
);



COPY INTO PORTFOLIO_DB_RAW.RAW.OPS_FACT_INVENTORY_DAILY
FROM @PORTFOLIO_DB_RAW.RAW.CSV_LOAD_STAGE
FILES = ('FACT_INVENTORY_DAILY.csv')
FILE_FORMAT = (
    FORMAT_NAME = PORTFOLIO_DB_RAW.RAW.CSV_FORMAT
)
MATCH_BY_COLUMN_NAME = 'CASE_INSENSITIVE'
ON_ERROR = 'ABORT_STATEMENT';